### ISSUE TITLE
Provide downloads via curseforge.com instead of curse.com

### ISSUE THREAD

**Issue by Jiraiyah** [minecraftforum/widget#24]
Hi
i'm sure i'm one of few unlucky guys out there that lives in the country that blocks curse.com but curseforge is open, so is it possible to make it so that the widget in forums refer to correct curseforge instead of curse.com itself?
thanks

**Comment by The-Fireplace** [comment]
I see the usefulness in this as well, for a different reason. Correct me if I am wrong, but it takes approximately 2 hours for a file to go from being approved on CurseForge to showing up on the widget, 1 hour to show up on Curse, and another hour before the widget updates. If the widget were to work directly from CurseForge, however, it would only take 1 hour.

**Comment by citricsquid** [comment]
To keep you in the loop, development on the widget is frozen and has been for quite a while. Long story short, I reached a lot of limits with what I could do with the widget, and then there had been internal discussion at Curse about building out the widget as an official part of CurseForge which led me to conclude there wasn't any justification for continuing work on the project when it was (I expected) to be shuttered in a few months, as the replacement *official* CurseForge widget would be far superior. Unfortunately as far as I can tell there hasn't been an official CurseForge widget launched which means people are still reliant on this project, we're currently pushing over 5 million widget renders per month. I'm going to follow up with the CurseForge team ASAP to find out where exactly they're at with the official Widget, and if necessary may resume development on this project as alongside a number of requests from users, there are improvements I'd like to make (no promises though...). 

> If the widget were to work directly from CurseForge, however, it would only take 1 hour.

The reason that the widget pulls from curse.com rather than curseforge.com is primarily because curse.com is the consumer part of CurseForge and I wanted the widget to respect that[1], but it's also because curse.com provides the data in a standardised way, whereas CurseForge varies from game to game. An important consideration when developing the widget was making it as simple as possible for both use and development, it would have been challenging to stay simple while supporting multiple different "versions" of CurseForge, for example: a World of Warcraft project (example: [Dominos](http://wow.curseforge.com/addons/dominos/)) and a Minecraft project (example: [Tinker's Construct](http://minecraft.curseforge.com/mc-mods/74072-tinkers-construct)) differ significantly on CurseForge.

I could conceivably have designed the widget to pull data from CurseForge while continuing to funnel users through curse.com, but given the complexity of pulling data from all the different versions of CurseForge it didn't seem worth it.

[1] Also, as I understand it, author rewards (the financial payouts from CurseForge) are driven by revenue generated on curse.com when downloads happen, CurseForge conversely does not generate revenue meaning if the widget funnelled users through CurseForge it would reduce the amount of money available to authors (and Curse too).
