### ISSUE TITLE
Additional Files are shown

### ISSUE THREAD

**Issue by Guichaguri** [minecraftforum/widget#38]
Additional Files should not be shown in the widget because they are not real releases of the mod.

This seems to be a problem with my project, because EE3 is not having the same issue.

Lastest File: http://minecraft.curseforge.com/projects/tickratechanger/files/2250609
Widget: http://widget.mcf.li/mc-mods/minecraft/230233-tickratechanger

EE3 Lastest File: http://minecraft.curseforge.com/projects/ee3/files/2239230
EE3 Widget: http://widget.mcf.li/mc-mods/minecraft/ee3

**Comment by citricsquid** [comment]
The widget doesn't pull in files from curseforge.com, instead it pulls from curse.com because that is the "consumer" portion of CurseForge -- or at least, that's my understanding. The curse.com page for your mod will display any file marked as **beta** or **release** (no alpha files), and the widget will default to displaying files marked as **release** with the option to include beta files (if you specify beta in the version parameter).

If you visit the [curse.com page for your mod](http://www.curse.com/mc-mods/minecraft/230233-tickratechanger#t1:other-downloads) you'll see that the file you're seeing in the widget "v1.0.2c DEV" is marked as a release, which is why the widget is defaulting to it. The reason this isn't happening for EE3 is because the parent file is marked as beta, whereas your parent file is marked as a release. 

The problem seems to be a bug with curse.com, and there's no data exposed on the curse.com page for your mod that I can access to determine automatically if a file is an "additional" file to a release. I'll take a look around and see what I can do but unfortunately, for now, it seems that you can't attach beta files to a release (as "additional files") without this happening.

As a potential temporary "solution", if you're using the widget, you can override the file selection by specifying a file ID, although this won't help for third parties using the widget API to retrieve information about your mod.

**Comment by Guichaguri** [comment]
For a workaround, I had to mark my files as alpha.
Thanks for your fast reply :)

**Comment by citricsquid** [comment]
Great! That's not ideal but it's better than my suggested workaround. I'll file a bug with the curse.com team about this, in the mean time I'll make a note about this in case anybody else has problems :) Thank you for letting me know about the workaround.
